### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/liftoff-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Programming the CARDIAC

- [ ] liftoff.cardiac code exists
- [ ] liftoff.cardiac uses the halt instruction
- [ ] liftoff.cardiac uses the accumulator to track and store values
- [ ] liftoff.cardiac output instruction to display countdown status
- [ ] looping.cardiac uses the JMP opcode
- [x] breaking.cardic uses the INP opcode
- [x] breaking.cardic uses the JMP opcode
- [x] breaking.cardic uses the TAC opcode
- [x] breaking.cardiac uses the halt instruction

## Documentation

- [ ] Answer all of the questions in the report

## Percent complete

Based on the checks achieved, this assignment is `40%` complete.
